### ISSUE TITLE
MVP / Minimum Viable Product / TODO

### ISSUE THREAD

**Issue by carstenhag** [Moter8/QuizIt#1]
## Aplicación Quiz It
- [x] 4 Respuestas por Pregunta
- [ ] Preguntas por Categoria
- [ ] Categorias aleatorias
- [x] Poder poner preguntas dentro de la aplicacion
- [ ] Cuentas con foto de perfil, Estadisticas
- [ ] Lista de Amigos/Contactos
- [x] Comodines: 50-50 y Comodin de tener mas tiempo
- [ ] Logros: integración con servicios Google
- [ ] Habilidad de ganar fichas de juego o monedas con las cuales se puedan comprar comodines
- [ ] Tragaperras o similar para ganar comodines, bonificacion si es jugador regular

**Comment by carstenhag** [comment]
Lo siguiente que hará será poner más categorías y preguntas de múltiples categorías.

**Comment by MRPixelMC** [comment]
JAJA
